apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  goidc.json: {{ include "oidcconfig" . | b64enc }}
