apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-image-puller
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    group: {{ .Release.Name }}-jupyterhub
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: image-puller
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      group: {{ .Release.Name }}-jupyterhub
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: image-puller
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        group: {{ .Release.Name }}-jupyterhub
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: image-puller
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    spec:
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
      initContainers:
        - name: image-pull-singleuser
          image: "{{ .Values.advanced.userImage }}"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 20m
              memory: 20M
            requests:
              cpu: 10m
              memory: 10M
          securityContext:
            runAsUser: 65534
          command:
            - /bin/sh
            - -c
            - 'echo "Pulling complete"'
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.0
          securityContext:
            runAsUser: 65534
          resources:
            limits:
              cpu: 20m
              memory: 20M
            requests:
              cpu: 10m
              memory: 10M
