apiVersion: v1
description: OPeNDAP Hyrax data server.
name: hyrax
version: 1.17.1-01
maintainers:
- name: NRIS
  email: nris@sigma2.no
home: https://www.opendap.org/software/hyrax-data-server/
icon: https://www.opendap.org/wp-content/uploads/2024/01/Logo-red-2.png
keywords:
  - OPeNDAP
  - Hyrax
