kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-hub-config
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  proxy-api: {{ .Release.Name }}-proxy-api
  hub: {{ .Release.Name }}-hub

{{- if ne (first .Values.persistentStorage).existingClaim "" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-minio
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  passwd: {{ include "minio-passwd" . | quote }}
  group: {{ include "minio-group" . | quote }}
{{- end }}
