apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-hub
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: hub
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app: {{ template "fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-hub
      component: hub
      release: {{ .Release.Name }}
