kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-hub-secret
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  proxy.token: {{ randAlphaNum 32 | b64enc | quote }}
   {{- $values := dict "hub" dict }}
  values.yaml: {{ $values | toYaml | b64enc | quote }}

{{ if .Values.advanced.sharedData.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-minio
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.advanced.minio.minioAccessKey | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.advanced.minio.minioSecretKey | b64enc }}
{{ end }}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ipyparallel-config
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $data := dict "Release" .Release "randomKey" (randAlphaNum 32 | b64enc) }}
  ipcontroller-engine.json: {{ include "ipcontroller_config" $data | b64enc | quote }}
  ipcontroller-client.json: {{ include "ipcontroller_client_config" $data | b64enc | quote }}
