ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: "2"
    memory: 2G
    gpu: 0
  limits:
    cpu: "4"
    memory: 2G
    gpu: 0
persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
    readOnly: false
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    scopes:
      - ""
    id: "0000-abc"
    owner: "0000-1234"
    client_secret: "0000-0000"
    authorized_groups:
      - ""
  aai:
    client_id: provided-by-toolkit
    client_secret: provided-by-toolkit
    issuer_url: https://apps-auth.sigma2.no/
    scopes:
      - openid
      - profile
      - email
    authorized_principals: []
uid: 999
gid: 999
username: vncuser
supplementalGroups:
  - name: ""
    gid: ""
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
advanced:
  dockerImage: quay.io/nird-toolkit/desktop-vnc:20220225-dd67aab
