advanced:
  workers:
    replicas: 1
    resources:
      requests:
          cpu: "2"
          memory: 2G
      limits:
          cpu: "4"
          memory: 2G

  master:
    resources:
      requests:
          cpu: "2"
          memory: 2G
      limits:
          cpu: "4"
          memory: 2G
  dockerImage: sigma2as/jupyter-spark:20240201-964601f

uid: 999
gid: 999
username: notebook
supplementalGroups:
  - name: ""
    gid: ""
ingress:
  host: "host.example.com"

persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
    readOnly: false

appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@sigma2.no"
  dataporten:
    scopes:
      - ""
    id: "0000"
    owner: "0000-1234"
    client_secret: "0000"
    authorized_groups:
      - ""
  aai:
    client_id: provided-by-toolkit
    client_secret: provided-by-toolkit
    issuer_url: https://apps-auth.sigma2.no/
    scopes:
      - openid
      - profile
      - email
    authorized_principals: []
    owner: provided-by-toolkit
    userinfo_url: provided-by-toolkit
    token_url: provided-by-toolkit
    auth_url: provided-by-toolkit
authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups
