apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-proxy-cleaner"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    group: {{ .Release.Name }}-jupyterhub
    app: {{ template "fullname" . }}
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
    # This is what defines this resource as a hook.
    # We need to delete the hub pod due to proxy token issue
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-proxy-cleaner"
      annotations:
        appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        group: {{ .Release.Name }}-jupyterhub
        app: {{ template "fullname" . }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{.Release.Name}}-pod-cleaner
      containers:
      - name: pod-clean-job
        image: "gurvin/kubectl:1.10.5"
        imagePullPolicy: IfNotPresent
        env:
        - name: RELEASE
          value: {{.Release.Name}}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        command:
          - /bin/sh
        args:
          - -c
          - -x
          - "kubectl --namespace=${NAMESPACE} --selector=release=${RELEASE},component=hub delete pod"
