apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-proxy-test.fullname" . }}
  labels:
    {{- include "auth-proxy-test.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth-proxy-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auth-proxy-test.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth-proxy-test.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: httpbin
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: httpbin
          readinessProbe:
            httpGet:
              path: /
              port: httpbin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: authentication-proxy
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: sigma2as/goidc-proxy:next
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
          resources: {}
          volumeMounts:
          - mountPath: /conf
            name: oidcconfig
          workingDir: /conf
      volumes:
      - name: oidcconfig
        secret:
          secretName: {{ include "auth-proxy-test.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
