apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-proxy-test.fullname" . }}
  labels:
    {{- include "auth-proxy-test.labels" . | nindent 4 }}
type: Opaque
data:
  goidc.json: {{ include "oidcconfig" . | b64enc }}
