ingress:
  host: "local-chart.example.com"

dockerImage: "sigma2as/apache:20230818-6bb736a"
resources:
  requests:
    cpu: "1"
    memory: 2G
  limits:
    cpu: "2"
    memory: 4G

persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
    readOnly: false

appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@uninett.no"
  dataporten:
    scopes:
      - ""
    id: "0000-abc"
    owner: "0000-1234"
    client_secret: "0000-0000"
    authorized_groups:
      - ""
  aai:
    client_id: provided-by-toolkit
    client_secret: provided-by-toolkit
    issuer_url: https://apps-auth.sigma2.no/
    scopes:
      - openid
      - profile
      - email
    authorized_principals: []
uid: 48
gid: 48
username: notebook

supplementalGroups:
  - name: ""
    gid: ""

authGroupProviders:
  - url: "https://groups-api.dataporten.no/groups/me/groups"
    scope: groups

mainHttpPort: 8080

advanced:
  customCommand: ""
  customEnv: []
  customArgs: []
  dataportenLoginProxy:
    enabled: true
  externalPort:
    enabled: false
