apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  default.conf: {{ include "default.conf" . | quote }}
  passwd: {{ include "passwd" . | quote }}
  group: {{ include "group" . | quote }}
  shadow: {{ include "shadow" . | quote }}
  shiny-server.conf: {{ include "shiny-server.conf" . | quote }}
  rserver.conf: {{ include "rserver.conf" . | quote }}
  rsession.conf: {{ include "rsession.conf" . | quote }}
  .Renviron: {{ include ".Renviron" . | quote }}
