ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: "2"
    memory: 2G
  limits:
    cpu: "4"
    memory: 2G
persistentStorage:
  existingClaim: ""
  existingClaimName: "example-name"
  subPath: "/"
  readOnly: false
uid: 999
gid: 999

username: minio
supplementalGroups:
  - name: ""
    gid: ""
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@sigma2.no"
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000"
    authorized_groups:
      - ""
  aai:
    client_id: provided-by-toolkit
    client_secret: provided-by-toolkit
    issuer_url: https://apps-auth.sigma2.no/
    scopes:
      - openid
      - profile
      - email
    authorized_principals: []
    owner: provided-by-toolkit
    userinfo_url: provided-by-tookit
    token_url: provided-by-toolkit
    auth_url: provided-by-toolkit
advanced:
  rootUser: "rootuserexample"
  rootPassword: "rootpasswordexample"
  dockerImage: sigma2as/minio:20240305-c6b5ed5
