ingress:
  host: "local-chart.example.com"
resources:
  requests:
    cpu: "2"
    memory: 2G
  limits:
    cpu: "4"
    memory: 2G
persistentStorage:
  - existingClaim: ""
    existingClaimName: "example-name"
    subPath: "/"
    readOnly: false
uid: 999
gid: 999

username: minio
supplementalGroups:
  - name: ""
    gid: ""
appstore_generated_data:
  appstore_meta_data:
    contact_email: "example@sigma2.no"
  dataporten:
    scopes:
      - ""
    id: "0000"
    client_secret: "0000"
    authorized_groups:
      - ""
advanced:
  rootUser: "rootuserexample"
  rootPassword: "rootpasswordexample"
  dockerImage: sigma2as/minio:20240304-b7bc3d1
