apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
        app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      volumes:
        - name: oidcconfig
          secret:
            secretName: {{ template "fullname" . }}
      containers:
      - name: auth-proxy
        image: sigma2as/goidc-proxy:next
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
          - name: oidcconfig
            mountPath: /conf
        workingDir: /conf
      - name: dokuwiki
        image: quay.io/uninett/dokuwiki:20180727-30f3127
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 8888
        env:
          - name: DOKUWIKI_BASE_URL
            value: "https://{{ .Values.ingress.host }}"
