apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  goidc.json: {{ include "oidcconfig" . | b64enc }} 
