apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  annotations:
    appstore.uninett.no/contact_email: {{ .Values.appstore_generated_data.appstore_meta_data.contact_email }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  notebook_config.py: {{ include "notebook-config" . | quote }}
  passwd: {{ include "passwd" . | quote }}
  group: {{ include "group" . | quote }}
